version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"

  genetic-data-processing-service:
    build: ./genetic-data-processing-service
    ports:
      - "8001:8001"